name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet restore Geopilot.sln

      - name: Build dotnet
        run: dotnet build Geopilot.sln -c Release --no-restore /warnaserror
      - name: Run frontend ci install
        working-directory: ./src/Geopilot.Frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./src/Geopilot.Frontend
        run: npm run build --if-present

      - name: Lint frontend
        working-directory: ./src/Geopilot.Frontend
        run: npm run lint

      - name: Check migration history
        working-directory: ./src/Geopilot.Api
        run: dotnet tool run dotnet-ef migrations has-pending-model-changes

      - name: Start test db
        run: docker compose up -d --wait --wait-timeout 30 db

      - name: Test
        run: dotnet test Geopilot.sln -c Release --no-build --verbosity normal

