name: ZAP Scan

on: [push]

permissions:
  contents: read

jobs:
  zap-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0"

      - name: Setup dev-certs
        uses: ./.github/actions/setup-dev-certs

      - name: Start db and api's
        run: docker compose up --wait

      - name: ZAP full scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: "https://localhost:5173"
          rules_file_name: "./config/zap-full-scan-rules.tsv"
          fail_action: true
          allow_issue_writing: false
          artifact_name: "zap-full-scan-report"

  zap-api-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0"

      - name: Setup dev-certs
        uses: ./.github/actions/setup-dev-certs

      - name: Start db and api's
        run: docker compose up --wait

      - name: ZAP api scan
        uses: zaproxy/action-api-scan@v0.10.0
        with:
          target: "https://localhost:5173/swagger/v1/swagger.json"
          rules_file_name: "./config/zap-api-scan-rules.tsv"
          format: openapi
          fail_action: true
          allow_issue_writing: false
          artifact_name: "zap-api-scan-report"
